# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_next(object):
    def setupUi(self, Dialog_next):
        Dialog_next.setObjectName("Dialog_next")
        Dialog_next.resize(448, 356)
        self.pB_main_run = QtWidgets.QPushButton(Dialog_next)
        self.pB_main_run.setGeometry(QtCore.QRect(150, 300, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pB_main_run.setFont(font)
        self.pB_main_run.setObjectName("pB_main_run")
        self.zakaz = QtWidgets.QComboBox(Dialog_next)
        self.zakaz.setGeometry(QtCore.QRect(270, 210, 121, 31))
        self.zakaz.setObjectName("zakaz")
        self.status = QtWidgets.QComboBox(Dialog_next)
        self.status.setGeometry(QtCore.QRect(270, 250, 121, 31))
        self.status.setObjectName("status")
        self.label = QtWidgets.QLabel(Dialog_next)
        self.label.setGeometry(QtCore.QRect(50, 80, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_next)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_next)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog_next)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog_next)
        self.label_5.setGeometry(QtCore.QRect(50, 250, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog_next)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.splitter = QtWidgets.QSplitter(Dialog_next)
        self.splitter.setGeometry(QtCore.QRect(270, 80, 121, 121))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.sklad_mnlz = QtWidgets.QComboBox(self.splitter)
        self.sklad_mnlz.setObjectName("sklad_mnlz")
        self.sklad_nerez = QtWidgets.QComboBox(self.splitter)
        self.sklad_nerez.setObjectName("sklad_nerez")
        self.sklad_rez = QtWidgets.QComboBox(self.splitter)
        self.sklad_rez.setObjectName("sklad_rez")
        self.Text_path = QtWidgets.QTextEdit(Dialog_next)
        self.Text_path.setGeometry(QtCore.QRect(140, 20, 251, 41))
        self.Text_path.setObjectName("Text_path")

        self.retranslateUi(Dialog_next)
        QtCore.QMetaObject.connectSlotsByName(Dialog_next)

    def retranslateUi(self, Dialog_next):
        _translate = QtCore.QCoreApplication.translate
        Dialog_next.setWindowTitle(_translate("Dialog_next", "Dialog"))
        self.pB_main_run.setText(_translate("Dialog_next", "Запуск"))
        self.label.setText(_translate("Dialog_next", "Склад МНЛЗ"))
        self.label_2.setText(_translate("Dialog_next", "Склад нерез"))
        self.label_3.setText(_translate("Dialog_next", "Склад резаных"))
        self.label_4.setText(_translate("Dialog_next", "Заказ"))
        self.label_5.setText(_translate("Dialog_next", "Статус произв"))
        self.label_6.setText(_translate("Dialog_next", "Папка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_next = QtWidgets.QDialog()
    ui = Ui_Dialog_next()
    ui.setupUi(Dialog_next)
    Dialog_next.show()
    sys.exit(app.exec_())

